# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eljam3239/repos/snackmap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eljam3239/repos/snackmap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eljam3239/repos/snackmap/CMakeFiles /home/eljam3239/repos/snackmap//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eljam3239/repos/snackmap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sqlite3

# Build rule for target.
sqlite3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqlite3
.PHONY : sqlite3

# fast build rule for target.
sqlite3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite3.dir/build.make CMakeFiles/sqlite3.dir/build
.PHONY : sqlite3/fast

#=============================================================================
# Target rules for targets named snackmap

# Build rule for target.
snackmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snackmap
.PHONY : snackmap

# fast build rule for target.
snackmap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/build
.PHONY : snackmap/fast

controller/UserController.o: controller/UserController.cpp.o
.PHONY : controller/UserController.o

# target to build an object file
controller/UserController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/controller/UserController.cpp.o
.PHONY : controller/UserController.cpp.o

controller/UserController.i: controller/UserController.cpp.i
.PHONY : controller/UserController.i

# target to preprocess a source file
controller/UserController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/controller/UserController.cpp.i
.PHONY : controller/UserController.cpp.i

controller/UserController.s: controller/UserController.cpp.s
.PHONY : controller/UserController.s

# target to generate assembly for a file
controller/UserController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/controller/UserController.cpp.s
.PHONY : controller/UserController.cpp.s

lib/sqlite3.o: lib/sqlite3.c.o
.PHONY : lib/sqlite3.o

# target to build an object file
lib/sqlite3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite3.dir/build.make CMakeFiles/sqlite3.dir/lib/sqlite3.c.o
.PHONY : lib/sqlite3.c.o

lib/sqlite3.i: lib/sqlite3.c.i
.PHONY : lib/sqlite3.i

# target to preprocess a source file
lib/sqlite3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite3.dir/build.make CMakeFiles/sqlite3.dir/lib/sqlite3.c.i
.PHONY : lib/sqlite3.c.i

lib/sqlite3.s: lib/sqlite3.c.s
.PHONY : lib/sqlite3.s

# target to generate assembly for a file
lib/sqlite3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlite3.dir/build.make CMakeFiles/sqlite3.dir/lib/sqlite3.c.s
.PHONY : lib/sqlite3.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/main.cpp.s
.PHONY : main.cpp.s

model/DatabaseManager.o: model/DatabaseManager.cpp.o
.PHONY : model/DatabaseManager.o

# target to build an object file
model/DatabaseManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/model/DatabaseManager.cpp.o
.PHONY : model/DatabaseManager.cpp.o

model/DatabaseManager.i: model/DatabaseManager.cpp.i
.PHONY : model/DatabaseManager.i

# target to preprocess a source file
model/DatabaseManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/model/DatabaseManager.cpp.i
.PHONY : model/DatabaseManager.cpp.i

model/DatabaseManager.s: model/DatabaseManager.cpp.s
.PHONY : model/DatabaseManager.s

# target to generate assembly for a file
model/DatabaseManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/model/DatabaseManager.cpp.s
.PHONY : model/DatabaseManager.cpp.s

model/UserModel.o: model/UserModel.cpp.o
.PHONY : model/UserModel.o

# target to build an object file
model/UserModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/model/UserModel.cpp.o
.PHONY : model/UserModel.cpp.o

model/UserModel.i: model/UserModel.cpp.i
.PHONY : model/UserModel.i

# target to preprocess a source file
model/UserModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/model/UserModel.cpp.i
.PHONY : model/UserModel.cpp.i

model/UserModel.s: model/UserModel.cpp.s
.PHONY : model/UserModel.s

# target to generate assembly for a file
model/UserModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snackmap.dir/build.make CMakeFiles/snackmap.dir/model/UserModel.cpp.s
.PHONY : model/UserModel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... snackmap"
	@echo "... sqlite3"
	@echo "... controller/UserController.o"
	@echo "... controller/UserController.i"
	@echo "... controller/UserController.s"
	@echo "... lib/sqlite3.o"
	@echo "... lib/sqlite3.i"
	@echo "... lib/sqlite3.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model/DatabaseManager.o"
	@echo "... model/DatabaseManager.i"
	@echo "... model/DatabaseManager.s"
	@echo "... model/UserModel.o"
	@echo "... model/UserModel.i"
	@echo "... model/UserModel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

